# -*- coding: utf-8 -*-
"""Codigos de erro PEFIN (3 digitos) extraidos de ARQUIVO SERASA/PEFIN - TABELA DE ERROS.pdf.

Usado ao interpretar TXT de retorno SERASA: codigos de 3 digitos na zona apos o codigo do credor
(posicoes 531-593 inclusive, base 1), conforme amostras em ``ARQUIVO SERASA/Retorno/*.TXT``.
"""
from __future__ import annotations

import re

LINHA_DETALHE_PEFIN_LEN = 600

PEFIN_CODIGO_ERRO_DESCRICAO = {
    '000': 'REGISTRO AR - ASSINADO',
    '002': 'PRIMEIRO REGISTRO NAO E HEADER/SEQUENCIA DIFERENTE DE 1',
    '003': 'REGISTRO DIFERENTE DE 0, 1 E 9',
    '004': 'REGISTRO FORA DE SEQUENCIA',
    '005': 'REGISTRO TRAILLER NAO INFORMADO',
    '008': 'CODIGO DE OPERACAO DIFERENTE DE E, I',
    '009': 'TIPO DE PESSOA PRINCIPAL DIFERENTE DE F, J',
    '010': 'TIPO DE PESSOA COOBRIGADO DIFERENTE DE F, J',
    '011': 'NOME INVALIDO',
    '012': 'NOME NAO PODE SER BRANCOS',
    '013': 'DATA DO HEADER INVALIDA',
    '014': 'DATA DA OCORRENCIA INVALIDA',
    '016': 'DATA DA OCORRENCIA MAIOR QUE A ATUAL',
    '017': 'DATA DA OCORRENCIA JA DECURSADA',
    '018': 'IDENTIFICACAO DO ARQUIVO INVALIDA',
    '019': 'REMESSA NAO POSTERIOR A ULTIMA',
    '020': 'REMESSA NAO NUMERICA OU IGUAL A ZERO',
    '021': "CAMPO DE RECEBIMENTO DA REMESSA DIFERENTE DE 'E'",
    '022': 'EXCLUSAO PARA REGISTRO INEXISTENTE',
    '024': 'CNPJ DO HEADER INVALIDO',
    '025': 'CNPJ NAO CADASTRADO NO SISTEMA (TABELA DE REMESSA)',
    '028': 'DOCUMENTO DO PRINCIPAL NAO NUMERICO',
    '029': 'DOCUMENTO DO PRINCIPAL INVALIDO',
    '030': 'DOCUMENTO DO COOBRIGADO NAO NUMERICO',
    '031': 'DOCUMENTO DO COOBRIGADO INVALIDO',
    '033': 'TRAILLER FORA DE SEQUENCIA',
    '034': 'SEQUENCIA NAO NUMERICA',
    '040': 'REG. NAO ATUALIZADO. ERRO NO PRINCIPAL OU COOBRIGADO DA OCORRENCIA',
    '044': 'AGENCIA INVALIDA',
    '047': 'CONTA NAO NUMERICA',
    '059': 'INCLUSAO PARA REGISTRO JA EXISTENTE',
    '064': 'CONTA INVALIDA',
    '065': 'CHEQUE INVALIDO',
    '072': 'ALINEA INVALIDA',
    '081': 'REGISTRO APOS TRAILLER',
    '085': 'NUMERO DO CONTRATO/TITULO INVALIDO',
    '089': 'EMPRESA NAO PARTICIPANTE DO CONVENIO',
    '102': 'NUMERO DO CONTRATO/TITULO EH OBRIGATORIO',
    '103': 'TIPO DE DOCUMENTO INVALIDO',
    '105': 'INCLUSAO BLOQUEADA FACE A DETERMINACAO ADMINISTRATIVA',
    '106': 'MOVIMENTO APOS RESCISAO DE CONTRATO DO CONVENIO',
    '109': 'FALTA ENDERECO',
    '111': 'FALTA UF DO ENDERECO',
    '112': 'FALTA CEP DO ENDERECO',
    '113': 'FALTA INFORMACAO TIPO DE PESSOA',
    '115': 'TIPO DE PESSOA DO PRINCIPAL DIFERENTE DE F',
    '116': 'TIPO DE PESSOA DO COOBRIGADO DIFERENTE DE F',
    '119': 'CEP DO ENDERECO INVALIDO',
    '121': 'DATA DE NASCIMENTO INFERIOR A 18 ANOS',
    '142': 'BANCO NAO TRABALHA COM CONTA CORRENTE',
    '156': 'DATA OCORRENCIA INFERIOR A 1 DIA',
    '166': 'DATA DE TERMINO DO CONTRATO INVALIDA',
    '169': 'AREA INFORMANTE DA REMESSA C/ ERRO. MOVIMENTO REJEITADO',
    '170': 'BANCO INVALIDO P/ NATUREZA DE/DC',
    '171': 'TIPO DE PESSOA DO CREDOR DIFERENTE DE F, J',
    '172': 'TIPO DE DOCUMENTO DO CREDOR INVALIDO',
    '173': 'DOCUMENTO DO CREDOR NAO NUMERICO',
    '174': 'DOCUMENTO DO CREDOR INVALIDO',
    '175': 'NOME DO CREDOR EH OBRIGATORIO',
    '176': 'NOME DO CREDOR INVALIDO',
    '200': 'BANCO DO HEADER INVALIDO',
    '205': 'BANCO NAO CADASTRADO NO SISTEMA (TABELA DE BANCOS)',
    '219': 'VALOR DO TITULO INVALIDO',
    '263': 'IDENTIFICACAO DO ARQUIVO INVALIDA',
    '274': 'CNPJ NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
    '275': 'CPF NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
    '276': 'FILIAL NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
    '277': 'CNPJ CREDOR/CEDENTE NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
    '278': 'CPF CREDOR/CEDENTE NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
    '279': 'FILIAL CREDOR/CEDENTE NAO EXISTE CADASTRO DE CNPJ/CPF ATE ESTA DATA',
    '286': 'DOCUMENTO DO CREDOR IGUAL AO DO NEGATIVADO',
    '290': 'EXCLUSAO POR DATA DE OCORRENCIA JA DECURSADA',
    '291': 'EXCLUSAO POR DETERMINACAO JUDICIAL',
    '292': 'EXCLUSAO POR SOLICITACAO DA EMPRESA PARTICIPANTE',
    '295': 'RAZAO SOCIAL NAO CORRESPONDE AO CNPJ INFORMADO',
    '296': 'NOME NAO CORRESPONDE AO CPF INFORMADO',
    '298': 'COOBRIGADO NAO INCLUIDO - PRINCIPAL NAO ENCONTRADO',
    '301': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - MUDOU-SE',
    '302': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - END INSUFICIENTE',
    '303': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - NR INEXISTENTE',
    '304': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - DESCONHECIDO',
    '305': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - RECUSADO',
    '306': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - NAO PROCURADO',
    '307': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - AUSENTE',
    '308': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - FALECIDO',
    '309': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO CORREIO - INFORM P/ PORTEIRO',
    '310': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - END N CONHECIDO',
    '311': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - CEP INCORRETO',
    '312': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - N ESPECIFICADO',
    '313': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO CORREIO - CX POSTAL INEXIST',
    '314': 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO CORREIO - IMOVEL INEXISTENTE',
    '315': 'DEVIDO A DEVOLUCAO DO COMUNICADO DO CORREIO',
    '316': 'REGISTRO AR - EXTRAVIADO',
    '317': 'REGISTRO AR - ROUBADO',
    '318': 'REGISTRO AR - AUSENTE - ENCAMINHADO PARA ENTREGA INTERNA',
    '319': 'REGISTRO AR - REFUGADO',
    '320': 'REGISTRO AR - ENDERECO INCORRETO',
    '321': 'REGISTRO AR - NAO PROCURADO – DEVOLVIDO AO REMETENTE',
    '322': 'REGISTRO AR - DOCUMENTACAO NAO FORNECIDA',
    '323': 'REGISTRO AR - MUDOU-SE',
    '324': 'REGISTRO AR - DESCONHECIDO',
    '325': 'REGISTRO AR - RECUSADO',
    '326': 'REGISTRO AR - ENDERECO INSUFICIENTE',
    '327': 'REGISTRO AR - NAO EXISTE O NUMERO INDICADO',
    '328': 'REGISTRO AR - AUSENTE',
    '329': 'REGISTRO AR - NAO PROCURADO',
    '330': 'REGISTRO AR - FALECIDO',
    '331': 'REGISTRO AR - DEVIDO A DEVOLUCAO DO COMUNICADO DO CORREIO',
    '356': 'DATA DO COMPROMISSO MAIOR QUE A ATUAL',
    '357': 'DATA DO COMPROMISSO INVALIDA',
    '358': 'VALOR DO COMPROMISSO NAO NUMERICO',
    '359': 'DDD INVALIDO',
    '360': 'TELEFONE INVALIDO',
    '390': 'INCLUSAO RECUSADA - PARTICIPANTE COM LOGON BLOQUEADO',
    '391': 'REGISTRO REJEITADO - INCONSISTENCIA NO HEADER',
    '392': 'FALTA CODIGO CLIENTE NA RSREMESSA OU CODIGO NAO TEM 5 CARACTERE',
    '394': 'CNPJ NAO CORRESPONDE AO CODIGO DE CLIENTE INFORMADO',
    '396': 'INCLUSAO REJEITADA-VLR.CONS.ELEVADO-NEGAT.PRIMARIA-INCL.SISCONVEM',
    '488': 'PARTICIPANTE NAO POSSUI PROCURACAO DO CREDOR',
    '489': 'UF DO RG INVALIDO',
    '490': 'FALTAM DADOS CADASTRAIS DO CREDOR DA DIVIDA',
    '491': 'MUNICIPIO NAO CORRESPONDE AO CEP E/OU UF INFORMADO',
    '600': 'MENSAGEM NAO INFORMADA PELO GERENCIADOR',
    '610': 'INCLUSAO CONDICIONADA A APRESENTACAO DE DOCTO DA DIVIDA',
    '650': 'CODIGO DO BANCO INVALIDO',
    '651': 'BANCO NAO CADASTRADO',
    '652': 'DIGITO DO CODIGO DO BANCO INVALIDO',
    '653': 'NOME DO BANCO NAO INFORMADO',
    '654': 'CARACTERES DA LINHA DIGITAVEL INVALIDA',
    '655': 'PRIMEIRO DIGITO DA LINHA DIGITAVEL DIVERGENTE',
    '656': 'SEGUNDO DIGITO DA LINHA DIGITAVEL DIVERGENTE',
    '657': 'TERCEIRO DIGITO DA LINHA DIGITAVEL DIVERGENTE',
    '658': 'QUARTO DIGITO DA LINHA DIGITAVEL DIVERGENTE',
    '659': 'TEXTO DO LOCAL DE PAGAMENTO NAO INFORMADO',
    '660': 'DATA DE VENCIMENTO DO BOLETO INVALIDA',
    '661': 'DATA DE VENCIMENTO DO BOLETO MENOR QUE A DATA DE HOJE',
    '662': 'TIPO DE PESSOA DO DOCUMENTO DO CEDENTE INVALIDO',
    '663': 'TIPO DE DOCUMENTO DO CEDENTE DIVERGENTE DO TIPO DE PESSOA',
    '664': 'DOCUMENTO DO CEDENTE INVALIDO',
    '665': 'DIGITO DO DOCUMENTO DO CEDENTE INVALIDO',
    '666': 'AGENCIA E CODIGO DO CEDENTE NAO INFORMADO',
    '667': 'DATA DO DOCUMENTO INVALIDA',
    '668': 'NUMERO DO DOCUMENTO NAO INFORMADO',
    '669': 'DATA DO PROCESSAMENTO INFORMADA E INVALIDA',
    '670': 'NOSSO NUMERO NAO INFORMADO',
    '671': 'QUANTIDADE DE MOEDA NAO INFORMADA',
    '672': 'QUANTIDADE DE MOEDA INVALIDA',
    '673': 'QUANTIDADE DE DECIMAIS DA MOEDA NAO INFORMADA',
    '674': 'QUANTIDADE DE DECIMAIS DA MOEDA INVALIDA',
    '675': 'QUANTIDADE DE DECIMAIS DA MOEDA MAIOR QUE 5 CASAS DECIMAIS',
    '676': 'VALOR DA MOEDA NAO INFORMADO',
    '677': 'VALOR DA MOEDA INVALIDA',
    '678': 'VALOR DO DOCUMENTO INVALIDO',
    '679': 'VALOR DE OUTROS ACRESCIMOS INVALIDO',
    '680': 'VALOR DE DESCONTOS/ABATIMENTO INVALIDO',
    '681': 'VALOR DE OUTRAS DEDUCOES INVALIDO',
    '682': 'VALOR DE MORA/MULTA INVALIDO',
    '683': 'VALOR COBRADO INVALIDO',
    '684': 'TIPO DE PESSOA DO DOCUMENTO DO SACADOR INVALIDO',
    '685': 'TIPO DE DOCUMENTO DO SACADOR DIVERGENTE DO TIPO DE PESSOA',
    '686': 'DOCUMENTO DO SACADOR INVALIDO',
    '687': 'DIGITO DO DOCUMENTO DO SACADOR INVALIDO',
    '701': 'EXISTE DADOS BOLETO E NAO INFORMADO INDICATIVO DE TIPO DE COMUNICADO',
    '702': "INDICATIVO DE TIPO DE COMUNICADO DIFERENTE DE BRANCO OU 'B'",
    '703': 'TIPO DE COMUNICADO COMO BOLETO E NAO FOI INFORMADO O REG.TP 2 E/OU 3',
    '704': 'TIPO DE COMUNICADO BOLETO NAO PERMITIDO PARA COOBRIGADO',
    '705': 'REG BOLETO TIPO 2 ENCONTRADO, SEM REGISTRO TIPO 1 CORRESPONDENTE',
    '706': 'REG BOLETO TIPO 3 ENCONTRADO, SEM REGISTRO TIPO 1 CORRESPONDENTE',
    '707': 'PARTICIPANTE NAO POSSUI CONTRATO PARA EMISSAO DE COMUNICADO COM BOLETO',
    '721': 'ENDERECO DO CEDENTE NAO CADASTRADO',
    '739': 'PARTICIPANTE NAO POSSUI CONTRATO PARA EMISSAO DE SMS.',
    '740': 'TELEFONE CELULAR INEXISTENTE',
    '745': 'INCLUSOES REJEITADAS - ESCRITORIO DE COBRANCA',
}

def descricao_codigo_erro(codigo: str | None) -> str | None:
    """Retorna descricao legivel ou None se codigo desconhecido."""
    if not codigo:
        return None
    c = str(codigo).strip().zfill(3)[-3:]
    return PEFIN_CODIGO_ERRO_DESCRICAO.get(c)


def extrair_codigos_erro_zona_retorno(linha: str) -> list[str]:
    """Codigos de erro de 3 digitos na zona de retorno (pos. 531-593, base 1)."""
    if len(linha) < 593:
        return []
    zona = linha[530:593]
    return re.findall(r'(?<!\d)\d{3}(?!\d)', zona)


def parse_linha_detalhe_pefin_retorno(linha: str) -> dict | None:
    """Linha de detalhe 600 chars: ``1I`` (inclusao) ou ``1E`` (exclusao), layout SERASA-CONVEM."""
    if len(linha) != LINHA_DETALHE_PEFIN_LEN or linha[0] != '1' or linha[1] not in ('I', 'E'):
        return None
    bloco = linha[31:50]
    doc15 = re.sub(r'\D', '', bloco[2:17] if len(bloco) >= 17 else bloco)
    doc15 = doc15[-15:].zfill(15) if doc15 else ''
    contrato16 = re.sub(r'\D', '', linha[438:454])
    contrato16 = contrato16[-16:].zfill(16) if contrato16 else '0' * 16
    try:
        valor_centavos = int(linha[423:438])
    except ValueError:
        valor_centavos = 0
    seq_linha = linha[593:600].strip()
    return {
        'tipo_operacao_ie': linha[1],
        'data_referencia_yyyymmdd': linha[8:16].strip(),
        'data_vencimento_yyyymmdd': linha[16:24].strip(),
        'documento_15': doc15,
        'contrato_nrs_16': contrato16,
        'valor_centavos': valor_centavos,
        'sequencial_linha_arquivo': seq_linha,
        'codigos_erro': extrair_codigos_erro_zona_retorno(linha),
    }
